
import { Item, Log, TransactionType, Partner } from './types';

export const CATEGORIES = ['탱크', '필터', '소금', '부품', '기타'];

export const INITIAL_PARTNERS: Partner[] = [
  { id: 'p1', name: '정연금속', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p2', name: '비에이치(2공장)', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p3', name: '선진기업', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p4', name: '대일매스램', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p5', name: '에이스파인켐', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p6', name: '백송전자', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p7', name: '정우테크', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p8', name: '동양시약', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p9', name: '아이엔씨', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p10', name: '정진금속', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p11', name: '동원화공', type: 'CUSTOMER', address: '인천 부평' },
  { id: 'p12', name: '비에이치(본사)', type: 'CUSTOMER', address: '인천 부평' },
  { id: 'p13', name: '넥스에이피엘', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p14', name: '엘에스포텍', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p15', name: '진성금속', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p16', name: '에스비골드', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p17', name: '엠알메탈로', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p18', name: '쓰리디테크', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p19', name: '일광테크', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p20', name: '이노플렉스', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p21', name: '한창기업', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p22', name: '한신단자공업', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p23', name: '마이크로켐텍', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p24', name: '신한다이아몬드(남동)', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p25', name: '프로엠텍', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p26', name: '신테크', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p27', name: '하이텍전자', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p28', name: '창원금속', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p29', name: '경방산업', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p30', name: '공성', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p31', name: '동성인더스트리', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p32', name: '씨앤씨테크', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p33', name: '신유메탈', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p34', name: '디지콘셉코리아', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p35', name: '현성전자', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p36', name: '그로피아', type: 'CUSTOMER', address: '인천 검단' },
  { id: 'p37', name: '윤재화학', type: 'CUSTOMER', address: '인천 검단' },
  { id: 'p38', name: '마텍스코리아', type: 'CUSTOMER', address: '인천 검단' },
  { id: 'p39', name: '지엘케이글로벌', type: 'CUSTOMER', address: '인천 검단' },
  { id: 'p40', name: '동지케미칼', type: 'CUSTOMER', address: '인천 검단' },
  { id: 'p41', name: '신한다이아몬드(R&D)', type: 'CUSTOMER', address: '인천 송도' },
  { id: 'p42', name: '에르가', type: 'CUSTOMER', address: '경기 부천' },
  { id: 'p43', name: '희망테크프론', type: 'CUSTOMER', address: '경기 부천' },
  { id: 'p44', name: '한국특수금속', type: 'CUSTOMER', address: '경기 부천' },
  { id: 'p45', name: '이화교역', type: 'CUSTOMER', address: '경기 일산' },
  { id: 'p46', name: '케이엘티', type: 'CUSTOMER', address: '경기 파주' },
  { id: 'p47', name: '에스엘씨', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p48', name: '대일테크', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p49', name: '동양화학상사', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p50', name: '디엠티(안산)', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p51', name: '케드켐', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p52', name: '연이합성산업', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p53', name: '에이피텍', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p54', name: '한빛케미칼', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p55', name: '성진전자', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p56', name: '에이치큐인터네셔널', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p57', name: '우성프레이팅', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p58', name: '한국피엠지제약', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p59', name: '케이에스씨', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p60', name: '화백엔지니어링', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p61', name: '부림화공약품', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p62', name: '신이이엔지', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p63', name: '현성테크놀로지', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p64', name: '대일산업', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p65', name: '진영엘이', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p66', name: '오주바렐연마', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p67', name: '에스에프이', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p68', name: '혜성금속', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p69', name: '지피텍', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p70', name: '비알에스테크놀로지', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p71', name: '이에스티', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p72', name: '대양이엔아이', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p73', name: '다올텍', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p74', name: '신성프리시젼', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p75', name: '에이앤지솔루션', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p76', name: '아이씨에이치', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p77', name: '한국에이엠에프', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p78', name: '맥더미드', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p79', name: '위즈코트', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p80', name: '영일프레시젼', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p81', name: '유원전자', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p82', name: '기양금속공업', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p83', name: '창강화학', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p84', name: '현진전자', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p85', name: '대림케미칼', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p86', name: '마이크로티에스', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p87', name: '대성하이피', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p88', name: '피앤티', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p89', name: '스마트코리아피씨비', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p90', name: '서광케미칼', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p91', name: '태성', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p92', name: '인산', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p93', name: '창대도금', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p94', name: '아이케이텍', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p95', name: '니어플렉스', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p96', name: '다이나오포티', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p97', name: '대영특수', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p98', name: '태양정공', type: 'CUSTOMER', address: '인천 남동' },
  { id: 'p99', name: '이씨텍', type: 'CUSTOMER', address: '인천 검단' },
  { id: 'p100', name: '대한테크', type: 'CUSTOMER', address: '경기 시화' },
  { id: 'p101', name: '보성산업사', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p102', name: '성지금속', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p103', name: '제일알미늄', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p104', name: '한국터치스크린', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p105', name: '지오화인켐', type: 'CUSTOMER', address: '지방 구미' },
  { id: 'p106', name: '한국테크닉이앤씨', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p107', name: '강진(연우)', type: 'CUSTOMER', address: '인천 가좌' },
  { id: 'p108', name: '서남프레스', type: 'CUSTOMER', address: '경기 안산' },
  { id: 'p109', name: '영광금속', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p110', name: '수원금속', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p111', name: '씨에스이노베이션', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p112', name: '엘파니', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p113', name: '경성', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p114', name: '어스텍', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p115', name: '코아티앤티', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p116', name: '씨엔에스켐', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p117', name: '홍진', type: 'CUSTOMER', address: '경기 화성' },
  { id: 'p118', name: '위드웨이브', type: 'CUSTOMER', address: '경기 수지&동탄' },
  { id: 'p119', name: '주안이엔지', type: 'CUSTOMER', address: '경기 수지&동탄' },
  { id: 'p120', name: '에스피이노베이션', type: 'CUSTOMER', address: '경기 수지&동탄' },
  { id: 'p121', name: '골든플렛폼', type: 'CUSTOMER', address: '경기 수지&동탄' },
  { id: 'p122', name: '창환단자공업', type: 'CUSTOMER', address: '경기 수지&동탄' },
  { id: 'p123', name: '엑시노', type: 'CUSTOMER', address: '경기 수지&동탄' },
  { id: 'p124', name: '새한마이크로텍', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p125', name: '씨엔아이티', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p126', name: '나트', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p127', name: '리슨트', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p128', name: '새한텅스텐', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p129', name: '엠에스테크', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p130', name: '한비텍', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p131', name: '국일그래핀', type: 'CUSTOMER', address: '경기 성남&남양주' },
  { id: 'p132', name: '디에스테크노', type: 'CUSTOMER', address: '경기 이천&광주' },
  { id: 'p133', name: '코스맥스엔비티', type: 'CUSTOMER', address: '경기 이천&광주' },
  { id: 'p134', name: 'HNT', type: 'CUSTOMER', address: '경기 이천&광주' },
  { id: 'p135', name: '디엠에스', type: 'CUSTOMER', address: '경기 이천&광주' },
  { id: 'p136', name: '제이스테크', type: 'CUSTOMER', address: '경기 군포' },
  { id: 'p137', name: '펜타헨즈', type: 'CUSTOMER', address: '서울 가산' },
  { id: 'p138', name: '제이피', type: 'CUSTOMER', address: '지방 천안' },
  { id: 'p139', name: '석영테크', type: 'CUSTOMER', address: '지방 정남' },
  { id: 'p140', name: '대상', type: 'CUSTOMER', address: '지방 대전' },
  { id: 'p141', name: '코리아이플랫폼', type: 'CUSTOMER', address: '지방 대전' },
  { id: 'p142', name: '몰텍스', type: 'CUSTOMER', address: '지방 안성' },
  { id: 'p143', name: '에이에스티', type: 'CUSTOMER', address: '지방 천안' },
  { id: 'p144', name: '나노시스(대전)', type: 'CUSTOMER', address: '지방 대전' },
  { id: 'p145', name: '엔앤피', type: 'CUSTOMER', address: '지방 청주' },
  { id: 'p146', name: '한일정밀', type: 'CUSTOMER', address: '지방 천안' },
  { id: 'p147', name: '한진석영', type: 'CUSTOMER', address: '지방 안성' },
  { id: 'p148', name: '엠씨케이테크', type: 'CUSTOMER', address: '지방 대전' },
  { id: 'p149', name: '에스제이지이브이', type: 'CUSTOMER', address: '지방 충주' },
  { id: 'p150', name: '충남대학교', type: 'CUSTOMER', address: '지방 대전' },
  { id: 'p151', name: '파인에코', type: 'CUSTOMER', address: '지방 천안' },
  { id: 'p152', name: '디엠이', type: 'CUSTOMER', address: '지방 청주' },
  { id: 'p153', name: '포인트엔지니어링', type: 'CUSTOMER', address: '지방 아산' },
  { id: 'p154', name: '신성화학', type: 'CUSTOMER', address: '지방 세종' },
  { id: 'p155', name: '디엠티(대전)', type: 'CUSTOMER', address: '지방 대전' },
  { id: 'p156', name: '아이비텍', type: 'CUSTOMER', address: '지방 청주' },
  { id: 'p157', name: '에스비메탈', type: 'CUSTOMER', address: '지방 청주' },
  { id: 'p158', name: '다빈금속', type: 'CUSTOMER', address: '지방 천안' },
  { id: 'p159', name: '유티아이', type: 'CUSTOMER', address: '지방 예산' },
  { id: 'p160', name: '부창금속', type: 'CUSTOMER', address: '지방 천안' },
  { id: 'p161', name: '디엠티(아산)', type: 'CUSTOMER', address: '지방 아산' },
  { id: 'p162', name: '이엠에스', type: 'CUSTOMER', address: '지방 청주' },
  { id: 'p163', name: '화신전자', type: 'CUSTOMER', address: '지방 청주' },
  { id: 'p164', name: '엘베스트지에이티', type: 'CUSTOMER', address: '지방 음성' },
  { id: 'p165', name: '이노레스(음성)', type: 'CUSTOMER', address: '지방 음성' },
  { id: 'p166', name: '덕산하이메탈', type: 'CUSTOMER', address: '지방 울산' },
  { id: 'p167', name: '나노시스(대구)', type: 'CUSTOMER', address: '지방 대구' },
  { id: 'p168', name: '윤금사(구미)', type: 'CUSTOMER', address: '지방 구미' },
  { id: 'p169', name: '아이비텍(김해)', type: 'CUSTOMER', address: '지방 김해' },
  { id: 'p170', name: '윤금사(대구)', type: 'CUSTOMER', address: '지방 대구' }
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: '1',
    name: '9인치 순수탱크',
    category: '탱크',
    quantity: 45,
    safetyStock: 10,
    price: 35000,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    name: '12인치 순수탱크',
    category: '탱크',
    quantity: 28,
    safetyStock: 5,
    price: 48000,
    lastUpdated: new Date().toISOString(),
  }
];

export const INITIAL_LOGS: Log[] = [
  {
    id: '101',
    itemId: '1',
    itemName: '9인치 순수탱크',
    partnerId: 'p1',
    partnerName: '정연금속',
    type: TransactionType.IN,
    quantity: 50,
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    note: '초기 입고',
  }
];
